// <auto-generated />
namespace Java2NetPort.Tests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class addesseqnumb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addesseqnumb));
        
        string IMigrationMetadata.Id
        {
            get { return "201403111408309_addes seq numb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
